name: musa-550-fall-2022
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.23
  - nodejs=18.8
  - black=22.6.0
  - jupyterlab_code_formatter=1.5.3
  - pandas=1.4.3
  - openpyxl=3.0
  - matplotlib=3.5.3
  - notebook=6.4.12
  - ipython=8.4.0
  - jupyterlab=3.4.5
  - nbconvert=7.0.0
  - pip=22.2
  - altair=4.2.0
  - seaborn=0.11.2
  - vega_datasets=0.9.0
  - vega=3.6.0
  - geopandas=0.10.2
  - shapely=1.8.4
  - descartes=1.1.0
  - pyepsg=0.4.0
  - cartopy=0.20.3
  - mapclassify=2.4.3
  - contextily=1.2.0
  - bokeh=2.4.3
  - hvplot=0.8.1
  - holoviews=1.15.0
  - geoviews=1.9.5
  - xarray=2022.6.0
  - datashader=0.14.2
  - param=1.12.2
  - panel=0.13.1
  - rasterio=1.3.2
  - rasterstats=0.17.0
  - earthpy=0.9.4
  - requests=2.28.1
  - cenpy=1.0
  - selenium=4.4.0
  - beautifulsoup4=4.11.1
  - imageio=2.21.1
  - intake=0.6.6
  - intake-parquet=0.2.3
  - intake-xarray=0.6.1
  - dask=2021.8.1
  - fastparquet=0.8.3
  - python-snappy=0.6.0
  - pyarrow=9.0.0
  - s3fs=2022.7.1
  - tqdm=4.64.0
  - pandana=0.6.1
  - osmnet=0.1.6
  - osmnx=1.2.2
  - networkx=2.8.6
  - scikit-learn=1.1.2
  - flask=2.2.2
  - dash=2.6.1
  - tweepy=4.10.1
  - textblob=0.15.3
  - nltk=3.6.7
  - rio-toa=0.3.0
  - rioxarray=0.12.0
  - missingno=0.4.2
  - kneed=0.7.0
  - pip:
      - us==2.0.2
      - webdriver_manager==3.8.4
      - jupyter-panel-proxy==0.1.0
      - jupyter-server-proxy==3.2.1
      - pygeckodriver==0.31.0
      - carto2gpd==1.0.12
      - esri2gpd==1.0.13
